FROM alpine

RUN echo "https://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories \
    && apk add --no-cache \
        tmux \
        neofetch \
        httpie \
        neovim \
        htop \
        bpytop \
        exa \
        jq \
        the_silver_searcher \
        bat \
        fish \
        git \
        openssh \
        podman \
        kubectx \
        kubectl \
        k9s
