FROM ubuntu:22.04

ARG DEBIAN_FRONTEND=noninteractive

ENV PATH "/opt/beekeeper:${PATH}"

RUN sed -i 's/archive.ubuntu/tr.archive.ubuntu/g' /etc/apt/sources.list \
  && apt update \
  && apt upgrade -y \
  && apt install -qqy wget gnupg2

RUN wget --quiet -O - https://deb.beekeeperstudio.io/beekeeper.key | apt-key add - \
  && echo "deb https://deb.beekeeperstudio.io stable main" | tee /etc/apt/sources.list.d/beekeeper-studio-app.list \
  && apt update -y \
  && apt install -qqy beekeeper-studio libgbm1 libasound2

RUN mv "/opt/Beekeeper Studio" "/opt/beekeeper" \
  && sed -i 's/\/opt\/Beekeeper Studio/\/opt\/beekeeper/g' /usr/share/applications/beekeeper-studio.desktop
