#!/bin/bash
# vim:set ft=bash et sw=4:

source scripts/common.bash

case "$(uname -s)" in

    Linux*)
      PLATFORM="linux"

      case "$(uname -i)" in

          x86_64) ARCH=amd64;;
          armv6l) ARCH=armhf;;
          *) die "Unknown architecture. Aborting."

      esac

      ;;

    Darwin*)
      PLATFORM="mac"

      case "$(uname -m)" in

          x86_64) ARCH=amd64;;
          armv6l) ARCH=armhf;;
          *) die "Unknown architecture. Aborting."

      esac

      ;;

    *) die "Unknown machine type. Aborting."

esac

export ARCH=$ARCH
export PLATFORM=$PLATFORM
export DOTFILES_ROOT=$(getDotFilesRoot)

if [[ "$PLATFORM" == "linux" ]]; then
    source $DOTFILES_ROOT/scripts/linux/install.bash
elif [[ "$PLATFORM" == "mac" ]]; then
    source $DOTFILES_ROOT/scripts/mac/install.bash
fi

separator

install settings/alacritty
install settings/editorconfig
install settings/fish
install settings/git
install settings/nvim
install settings/ssh
install settings/tmux

separator

clone https://github.com/tmux-plugins/tpm $HOME/.tmux/plugins/tpm

separator

# merge ssh configs
echo "Harnessing SSH configuration..."

# TODO: error handling

cat $HOME/.ssh/config_* > $HOME/.ssh/config
cat $HOME/.ssh/*.pub > $HOME/.ssh/authorized_keys

echo "Installation Complete!"
