- hosts: localhost

  vars:
    work:
      midas: true

    shell:
      program: /opt/homebrew/bin/fish
      arg: -l
      path: /opt/homebrew/bin ~/.cargo/bin
      font:
        size: 13

    gpg:
      bin: /usr/local/bin/gpg
      pinentry:
        bin: /usr/local/MacGPG2/libexec/pinentry-mac.app/Contents/MacOS/pinentry-mac
        mode: ask

    aliases:
      vim: lvim
      v: lvim

    abbrs:
      open: open
      rm: rm -i
      l: exa -lh --group-directories-first --all
      ll: exa -lh --group-directories-first
      lt: exa -lh --group-directories-first --all --tree
      lc: wc -l
      port: lsof -i

    brew:
      repos:
        - homebrew/cask
        - homebrew/cask-fonts

      packages:
        - asciinema
        - bash
        - bat
        - btop
        - direnv
        - exa
        - fish
        - fzf
        - golang
        - gpg
        - httpie
        - jq
        - neovim
        - node@18
        - openjdk@11
        - openjdk@17
        - podman
        - podman-compose
        - ripgrep
        - rustup-init
        - telnet
        - the_silver_searcher
        - tmux
        - uptimed
        - watch
        - wget
        - z

      casks:
        - 1password
        - brave-browser
        - caffeine
        - discord
        - firefox
        - font-fira-code-nerd-font
        - gpg-suite
        - jetbrains-toolbox
        - libreoffice
        - logitech-options
        - obsidian
        - openvpn-connect
        - postman
        - scroll-reverser
        - slack
        - spotify
        - tailscale
        - telegram-desktop
        - ticktick
        - visual-studio-code
        - wezterm
        - zoom

    installers:
      - golang
      - rust
      - nvm
      - cosign
      - dive
      - gh
      - kind
      - k9s
      - kubectl
      - kubectx
      - kubens
      - starship
      - zellij
      - lazygit
      - lunarvim

  roles:
    - brew
    - installers
    - configuration
    - mac
    - work
    - cleanup
