- hosts: localhost

  vars:
    configure:
      maven: true

    work:
      midas: true

    terminal:
      app: wezterm
      font:
        size: 13

    shell:
      bin: /opt/homebrew/bin/fish
      arg: -l
      path: /opt/homebrew/bin /opt/homebrew/sbin ~/.cargo/bin

    onepassword:
      enabled: true
      agent: ~/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock

    abbrs:
      pengudroid: scrcpy -eS --always-on-top --power-off-on-close

    aliases:
      just: just --unstable

    brew:
      repos:
        - esolitos/ipa # for sshpass
        - localsend/localsend
        - hashicorp/tap

      packages:
        - asciinema
        - awscli
        - bash
        - bat
        - btop
        - cosign
        - direnv
        - dive
        - eza
        - fish
        - fzf
        - gh
        - golang
        - gnu-tar
        - helm
        - httpie
        - ipcalc
        - jq
        - just
        - k9s
        - kind
        - krew
        - kubectl
        - kubectx
        - lazygit
        - localsend
        - minio-mc
        - neovim
        - openjdk@17
        - openjdk@21
        - podman-desktop
        - ripgrep
        - rustup-init
        - sshpass
        - starship
        - telnet
        - hashicorp/tap/terraform
        - the_silver_searcher
        - uptimed
        - watch
        - wget
        - zoxide
        - zellij

      casks:
        - 1password
        - 1password-cli
        - anydesk
        - balenaetcher
        - beekeeper-studio
        - brave-browser
        - caffeine
        - discord
        - firefox
        - font-fira-code-nerd-font
        - handbrake
        - jetbrains-toolbox
        - lens
        - libreoffice
        - logi-options-plus
        - windows-app
        - obsidian
        - openvpn-connect
        - protonvpn
        - postman
        - rar
        - scroll-reverser
        - slack
        - spotify
        - tailscale
        - telegram-desktop
        - ticktick
        - visual-studio-code
        - wezterm
        - wireshark
        - zoom

  roles:
    - brew
    - configuration
    - mac
    - work
