- hosts: localhost

  vars:
    work:
      midas: true

    shell:
      program: /opt/homebrew/bin/fish
      arg: -l
      path: /opt/homebrew/bin ~/.cargo/bin
      font:
        size: 13

    onepassword:
      enabled: true
      agent: ~/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock

    aliases:
      vim: lvim
      v: lvim
      just: just --unstable

    abbrs:
      open: open
      rm: rm -i
      l: exa -lh --group-directories-first --all
      ll: exa -lh --group-directories-first
      lt: exa -lh --group-directories-first --all --tree
      lc: wc -l
      port: lsof -i

    brew:
      repos:
        - esolitos/ipa # for sshpass
        - localsend/localsend
        - hashicorp/tap

      packages:
        - asciinema
        - awscli
        - bash
        - bat
        - btop
        - cosign
        - direnv
        - dive
        - exa
        - fish
        - fzf
        - gh
        - golang
        - gnu-tar
        - helm
        - httpie
        - ipcalc
        - jq
        - just
        - k9s
        - kind
        - krew
        - kubectl
        - kubectx
        - lazygit
        - localsend
        - minio-mc
        - neovim
        - nvim
        - openjdk@17
        - openjdk@21
        - podman-desktop
        - ripgrep
        - rustup-init
        - sshpass
        - telnet
        - hashicorp/tap/terraform
        - the_silver_searcher
        - tmux
        - uptimed
        - watch
        - wget
        - z

      casks:
        - 1password
        - 1password-cli-beta
        - balenaetcher
        - beekeeper-studio
        - brave-browser
        - caffeine
        - discord
        - firefox
        - font-fira-code-nerd-font
        - handbrake
        - jetbrains-toolbox
        - libreoffice
        - logi-options-plus
        - meetingbar
        - microsoft-remote-desktop
        - obsidian
        - openlens
        - openvpn-connect
        - protonvpn
        - postman
        - rar
        - scroll-reverser
        - slack
        - spotify
        - starship
        - tailscale
        - telegram-desktop
        - ticktick
        - visual-studio-code
        - wezterm
        - wireshark
        - zellij
        - zoom

    installers:
      - lunarvim

  roles:
    - brew
    - installers
    - configuration
    - mac
    - work
    - cleanup
