- hosts: localhost

  vars:
    configure:
      maven: true

    work:
      midas: true

    terminal:
      app: ghostty
      font:
        size: 13

    shell:
      bin: /opt/homebrew/bin/fish
      args: -l
      path: /opt/homebrew/bin /opt/homebrew/sbin ~/.cargo/bin

    onepassword:
      enabled: true
      agent: ~/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock

    aliases:
      l1: eza -1
      ls: eza
      ll: eza -l --icons=auto --group-directories-first

      grep: ug
      egrep: ug -E
      fgrep: ug -F
      xzgrep: ug -z
      xzegrep: ug -zE
      xzfgrep: ug -zF

      cat: bat --style=plain --pager=never

      v: nvim

    abbrs:
      pengudroid: scrcpy -eS --always-on-top --power-off-on-close

    brew:
      repos:
        - esolitos/ipa # for sshpass
        - localsend/localsend
        - hashicorp/tap
        - pamburus/tap
        - sst/tap

      packages:
        - asciinema
        - awscli
        - bash
        - bat
        - btop
        - cosign
        - direnv
        - dive
        - eza
        - fish
        - fzf
        - gh
        - gnu-tar
        - golang
        - hashicorp/tap/terraform
        - helm
        - hl
        - httpie
        - ipcalc
        - jq
        - just
        - k9s
        - kind
        - krew
        - kubectl
        - kubectx
        - lazygit
        - localsend
        - luarocks
        - minio-mc
        - neovim
        - opencode
        - openjdk@17
        - openjdk@21
        - ripgrep
        - rustup
        - sshpass
        - starship
        - telnet
        - the_silver_searcher
        - ugrep
        - uptimed
        - watch
        - wget
        - zellij
        - zoxide

      casks:
        - 1password
        - 1password-cli@beta
        - balenaetcher
        - beekeeper-studio
        - brave-browser
        - caffeine
        - discord
        - firefox
        - font-jetbrains-mono
        - ghostty
        - handbrake
        - jetbrains-toolbox
        - lens
        - libreoffice
        - logi-options-plus
        - obsidian
        - openvpn-connect
        - postman
        - protonvpn
        - rar
        - scroll-reverser
        - slack
        - spotify
        - tailscale
        - telegram-desktop
        - visual-studio-code
        - windows-app
        - zoom

  roles:
    - brew
    - configuration
    - mac
    - work
