- hosts: localhost

  vars:
    configure:
      maven: true

    work:
      midas: true

    aliases:
      v: nvim

    abbrs:
      pengudroid: scrcpy -eS --always-on-top --power-off-on-close

    terminal:
      window:
        width: 185
        height: 50

    gnome:
      extensions:
        install:
          - 2236 # night theme switcher
          - 7065 # tiling shell
          - 5410 # grand theft focus
          - 6162 # solaar extension
        enabled:
          - nightthemeswitcher@romainvigier.fr
          - caffeine@patapon.info
          - tilingshell@ferrarodomenico.com
          - grand-theft-focus@zalckos.github.com
          - solaar-extension@sidevesh
        disabled:
          - dash-to-dock@micxgx.gmail.com
          - logomenu@aryan_k
          - search-light@icedman.github.com

  roles:
    - linux
    - gnome
    - configuration
    - work
