- hosts: localhost

  vars:
    work:
      midas: true

    onepassword:
      enabled: true
      agent: ~/.1password/agent.sock

    aliases:
      vim: lvim
      v: lvim
      aws: op plugin run -- aws

    abbrs:
      rm: rm -i
      l: eza -lh --group-directories-first --all
      ll: eza -lh --group-directories-first
      lt: eza -lh --group-directories-first --all --tree
      lc: wc -l
      port: lsof -i

    brew:
      repos:
        - hashicorp/tap

      packages:
        - asciinema
        - awscli
        - btop
        - dive
        - golang
        - helm
        - httpie
        - k9s
        - kubectl
        - kubectx
        - lazygit
        - minio-mc
        - neovim
        - nvm
        - openjdk@17
        - openjdk@21
        - rustup-init
        - hashicorp/tap/terraform
        - the_silver_searcher
        - z
        - zellij

    installers:
      - lunarvim

    gnome:
      extensions:
        install:
          - 2236 # night theme switcher
          - 1460 # vitals
        enabled:
          - nightthemeswitcher@romainvigier.fr
          - Vitals@CoreCoding.com

    flatpaks:
      - app.drey.Warp
      - com.belmoussaoui.Decoder
      - com.belmoussaoui.Obfuscate
      - com.discordapp.Discord
      - com.getpostman.Postman
      - com.github.huluti.Curtail
      - com.github.maoschanz.drawing
      - com.gitlab.newsflash
      - com.google.Chrome
      - com.jetbrains.IntelliJ-IDEA-Community
      - com.protonvpn.www
      - com.rafaelmardojai.Blanket
      - com.slack.Slack
      - com.spotify.Client
      - com.usebottles.bottles
      - de.haeckerfelix.Fragments
      - de.haeckerfelix.Shortwave
      - fr.handbrake.ghb
      - io.gitlab.liferooter.TextPieces
      - io.github.seadve.Mousai
      - md.obsidian.Obsidian
      - org.gimp.GIMP
      - org.gnome.design.Lorem
      - org.gnome.gitlab.YaLTeR.VideoTrimmer
      - org.gnome.Snapshot
      - org.gnome.SoundRecorder
      - org.libreoffice.LibreOffice
      - org.raspberrypi.rpi-imager
      - org.telegram.desktop
      - org.videolan.VLC
      - org.wezfurlong.wezterm
      - us.zoom.Zoom

  roles:
    - brew
    - gnome
    - flatpak
    - configuration
    - installers
    - work
