- hosts: localhost

  vars:
    work:
      midas: true

    onepassword:
      enabled: true
      agent: ~/.1password/agent.sock

    aliases:
      vim: lvim
      v: lvim
      aws: op plugin run -- aws

    abbrs:
      rm: rm -i
      l: eza -lh --group-directories-first --all
      ll: eza -lh --group-directories-first
      lt: eza -lh --group-directories-first --all --tree
      lc: wc -l
      port: lsof -i

    brew:
      repos:
        - hashicorp/tap

      packages:
        - asciinema
        - awscli
        - btop
        - dive
        - golang
        - helm
        - httpie
        - k9s
        - kubectl
        - kubectx
        - lazygit
        - minio-mc
        - neovim
        - openjdk@17
        - openjdk@21
        - rustup-init
        - telnet
        - hashicorp/tap/terraform
        - the_silver_searcher
        - z
        - zellij

    installers:
      - lunarvim

    gnome:
      extensions:
        install:
          - 2236 # night theme switcher
          - 1460 # vitals
        enabled:
          - nightthemeswitcher@romainvigier.fr
          - pano@elhan.io

  roles:
    - brew
    - gnome
    - installers
    - configuration
    - work