- hosts: localhost

  vars:
    work:
      midas: true

    onepassword:
      enabled: true
      agent: ~/.1password/agent.sock

    ghostty:
      config_path: .var/app/com.mitchellh.ghostty/config/ghostty

    aliases:
      vim: lvim
      v: lvim

    abbrs:
      pengudroid: scrcpy -eS --always-on-top --power-off-on-close

    brew:
      repos:
        - hashicorp/tap

      packages:
        - asciinema
        - awscli
        - bat
        - btop
        - dive
        - eza
        - golang
        - helm
        - httpie
        - k9s
        - kubectl
        - kubectx
        - lazygit
        - minio-mc
        - neovim
        - nvm
        - openjdk@17
        - openjdk@21
        - ripgrep
        - rustup-init
        - sd
        - hashicorp/tap/terraform
        - the_silver_searcher
        - zoxide
        - zellij

      casks:
        - font-jetbrains-mono

    gnome:
      extensions:
        install:
          - 2236 # night theme switcher
          - 7065 # tiling shell
        enabled:
          - nightthemeswitcher@romainvigier.fr
          - caffeine@patapon.info
          - tilingshell@ferrarodomenico.com
        disabled:
          - dash-to-dock@micxgx.gmail.com
          - logomenu@aryan_k
          - search-light@icedman.github.com

    flatpaks:
      - app.drey.Damask
      - app.drey.Warp
      - com.belmoussaoui.Decoder
      - com.belmoussaoui.Obfuscate
      - com.brave.Browser
      - com.discordapp.Discord
      - com.getpostman.Postman
      - com.github.huluti.Curtail
      - com.google.Chrome
      - com.protonvpn.www
      - com.rafaelmardojai.Blanket
      - com.slack.Slack
      - com.spotify.Client
      - com.stremio.Stremio
      - com.usebottles.bottles
      - de.haeckerfelix.Fragments
      - de.haeckerfelix.Shortwave
      - dev.zed.Zed
      - fr.handbrake.ghb
      - in.srev.guiscrcpy
      - io.beekeeperstudio.Studio
      - io.github.nroduit.Weasis
      - io.github.seadve.Mousai
      - io.gitlab.liferooter.TextPieces
      - io.gitlab.news_flash.NewsFlash
      - it.mijorus.gearlever
      - md.obsidian.Obsidian
      - org.gimp.GIMP
      - org.gnome.Snapshot
      - org.gnome.SoundRecorder
      - org.gnome.design.Lorem
      - org.gnome.gitlab.YaLTeR.VideoTrimmer
      - org.gnome.seahorse.Application
      - org.libreoffice.LibreOffice
      - org.localsend.localsend_app
      - org.raspberrypi.rpi-imager
      - org.telegram.desktop
      - org.videolan.VLC
      - us.zoom.Zoom

  roles:
    - brew
    - gnome
    - flatpak
    - configuration
    - work
