- hosts: localhost

  vars:
    configure:
      maven: true

    work:
      midas: true

    aliases:
      oc: opencode
      v: nvim

    abbrs:
      pengudroid: scrcpy -eS --always-on-top --power-off-on-close

    terminal:
      window:
        width: 160
        height: 42

    gnome:
      extensions:
        install:
          - 2236 # night theme switcher
          - 7065 # tiling shell
          - 5410 # grand theft focus
          - 6162 # solaar extension
          - 1319 # gsconnect
          - 6139 # tailscale qs
          - 5489 # search light
          - 517 # caffeine
          - 615 # appindicator support
          - 3193 # blur my shell

  roles:
    - linux
    - gnome
    - configuration
    - work
