- hosts: localhost

  vars:
    work:
      midas: true

    gnome:
      extensions:
        install:
          - 615  # AppIndicator and KStatusNotifierItem Support
          - 3193 # blur my shell
          - 517  # caffeine
          - 1873 # Disable unredirect fullscreen windows
          - 1319 # GSConnect
          - 2236 # night theme switcher
          - 5278 # pano
          - 1460 # vitals
          - 5410 # grand theft focus
          - 4158 # GNOME 4x UI Improvements
        enabled:
          - appindicatorsupport@rgcjonas.gmail.com
          - blur-my-shell@aunetx
          - caffeine@patapon.info
          - unredirect@vaina.lt
          - gsconnect@andyholmes.github.io
          - nightthemeswitcher@romainvigier.fr
          - pano@elhan.io
          - Vitals@CoreCoding.com
          - grand-theft-focus@zalckos.github.com
          - gnome-ui-tune@itstime.tech
        disabled:
          - apps-menu@gnome-shell-extensions.gcampax.github.com
          - background-logo@fedorahosted.org
          - launch-new-instance@gnome-shell-extensions.gcampax.github.com
          - places-menu@gnome-shell-extensions.gcampax.github.com
          - window-list@gnome-shell-extensions.gcampax.github.com

    installers:
      - golang
      - rust
      - nvm
      - cosign
      - dive
      - gh
      - kind
      - k9s
      - kubectl
      - kubectx
      - kubens
      - starship
      - zellij
      - lazygit
      - lunarvim

    aliases:
      podman: podman --remote

    abbrs:
      open: xdg-open &> /dev/null
      rm: rm -i
      l: exa -lh --group-directories-first --all
      ll: exa -lh --group-directories-first
      lt: exa -lh --group-directories-first --all --tree
      lc: wc -l
      port: lsof -i

  roles:
    - fontconfig
    - gnome
    - configuration
    - installers
    - work
