- hosts: all

  vars:
    configure:
      ssh: false

    user:
      groups:
        - docker

    shell:
      bin: /usr/bin/fish

    abbrs:
      l: exa -lh --group-directories-first --all
      ll: exa -lh --group-directories-first
      lt: exa -lh --group-directories-first --all --tree

    aliases:
      bat: batcat

    repositories:
      - name: docker
        gpg_key: https://download.docker.com/linux/debian/gpg
        url: "deb [arch=arm64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian bookworm stable"

    packages:
      - bat
      - btop
      - exa
      - fish
      - git
      - htop
      - httpie
      - neovim
      - silversearcher-ag
      - zoxide
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin

  roles:
    - linux
    - configuration
