- hosts: all

  vars:
    configure:
      ssh: false

    shell:
      bin: /bin/fish

    abbrs:
      l: exa -lh --group-directories-first --all
      ll: exa -lh --group-directories-first
      lt: exa -lh --group-directories-first --all --tree

    packages:
      - bat
      - btop
      - exa
      - fish
      - htop
      - httpie
      - neovim
      - podman
      - podman-compose
      - podman-docker
      - silversearcher-ag
      - zoxide

  roles:
    - linux
    - configuration
