- hosts: localhost

  vars:
    work:
      ty: true

    shell:
      font:
        size: 12

    gpg:
      bin: /usr/local/bin/gpg
      pinentry:
        bin: /usr/local/MacGPG2/libexec/pinentry-mac.app/Contents/MacOS/pinentry-mac
        mode: ask

    abbrs:
      open: open
      rm: rm -i
      l: exa -lh --group-directories-first --all
      ll: exa -lh --group-directories-first
      lt: exa -lh --group-directories-first --all --tree
      lc: wc -l
      port: lsof -i

    brew:
      repos:
        - homebrew/cask
        - homebrew/cask-fonts

      packages:
        - asciinema
        - bash
        - bat
        - btop
        - direnv
        - exa
        - fish
        - fzf
        - gpg
        - httpie
        - jq
        - neovim
        - node@18
        - openjdk@11
        - openjdk@17
        - podman
        - podman-compose
        - ripgrep
        - rustup-init
        - the_silver_searcher
        - tmux
        - uptimed
        - watch
        - wget
        - z

      casks:
        - 1password
        - brave-browser
        - caffeine
        - font-fira-code-nerd-font
        - gpg-suite
        - jetbrains-toolbox
        - libreoffice
        - obsidian
        - postman
        - scroll-reverser
        - spotify
        - tailscale
        - telegram-desktop
        - visual-studio-code
        - wezterm
        - zoom

    installers:
      - kind
      - k9s
      - kubectl
      - kubectx
      - kubens
      - nvm
      - rust
      - zellij

  roles:
    - brew
    - installers
    - configuration
    - work
