- name: Configure desktop
  include_tasks: desktop/main.yml
  when: desktop.enabled

- name: Configure fonts
  include_tasks: common/fonts.yml
  when: fontconfig.enabled

- name: Configure wezterm
  include_tasks: common/wezterm.yml
  when: flatpak_packages | selectattr("name", "equalto", "org.wezfurlong.wezterm") | list | length > 0