- name: Configure dircolors
  include_tasks: ../common/dir_colors.yml

- name: Configure fonts
  include_tasks: ../common/fonts.yml
  when: fontconfig

- name: Configure alacritty
  include_tasks: ../common/alacritty.yml
  when: "'alacritty' in packages"

- name: Configure editorconfig
  file:
    src: "{{ role_path }}/files/editorconfig/editorconfig"
    dest: "{{ ansible_user_dir }}/.editorconfig"
    state: link
    force: true

- name: Configure fish
  include_tasks: ../common/fish.yml
  when: "'fish' in packages"

- name: Configure git
  file:
    src: "{{ role_path }}/files/git/gitconfig"
    dest: "{{ ansible_user_dir }}/.gitconfig"
    state: link
    force: true

- name: Configure neovim
  include_tasks: ../common/nvim.yml
  when: "'neovim' in packages"

- name: Configure ssh
  include_tasks: ../common/ssh.yml

- name: Configure tmux
  include_tasks: ../common/tmux.yml
  when: "'tmux' in packages"

- name: Configure distrobox
  include_tasks: ../common/distrobox.yml
  when: distrobox

- name: Configure desktop
  include_tasks: desktop/main.yml
  when: desktop.enabled
