- name: Place bat configuration
  copy:
    src: "{{ role_path }}/files/bat"
    dest: "{{ ansible_user_dir }}/.config"
    directory_mode: 0700
    mode: 0600
  notify:
    - Rebuild bat cache

- name: Install configuration file
  template:
    src: bat/config.j2
    dest: "{{ ansible_user_dir }}/.config/bat/config"
