- name: Place fish configuration
  file:
    src: "{{ role_path }}/files/fish"
    dest: $HOME/.config/fish
    state: link

- name: Place fish variables
  copy:
    src: fish/fish_variables.orig
    dest: $HOME/.config/fish/fish_variables
