- name: Create config directory
  file:
    path: "{{ ansible_user_dir }}/{{ ghostty.config_path }}"
    state: directory
    recurse: true

- name: Install configuration file
  template:
    src: ghostty/config.j2
    dest: "{{ ansible_user_dir }}/{{ ghostty.config_path }}/config"
