- name: Configure Linux
  include_tasks: linux/main.yml
  when: ansible_system == "Linux"

- name: Configure Mac
  include_tasks: mac/main.yml
  when: ansible_system == "Darwin"

- name: Create .m2/settings.xml
  copy:
    src: files/m2/
    dest: "{{ ansible_user_dir }}/.m2"
    directory_mode: 0700
    mode: 0600
