- name: Configure dircolors
  include_tasks: common/dir_colors.yml

- name: Configure editorconfig
  include_tasks: common/editorconfig.yml

- name: Configure fish
  include_tasks: common/fish.yml

- name: Configure git
  include_tasks: common/git.yml

- name: Configure gnupg
  include_tasks: common/gpg.yml

- name: Configure lvim
  include_tasks: common/lvim.yml

- name: Configure maven
  include_tasks: common/maven.yml

- name: Configure ssh
  include_tasks: common/ssh.yml

- name: Configure wezterm
  include_tasks: common/wezterm.yml

- name: Configure zellij
  include_tasks: common/zellij.yml
