- name: Configure dircolors
  include_tasks: colors.yml

- name: Configure editorconfig
  include_tasks: editorconfig.yml

- name: Configure fish
  include_tasks: fish.yml

- name: Configure git
  include_tasks: git.yml

- name: Configure lvim
  include_tasks: lvim.yml

- name: Configure maven
  include_tasks: maven.yml

- name: Configure ssh
  include_tasks: ssh.yml

- name: Configure wezterm
  include_tasks: wezterm.yml

- name: Configure zellij
  include_tasks: zellij.yml

- name: Configure starship
  include_tasks: starship.yml

- name: Configure k9s
  include_tasks: k9s.yml
