- name: Configure dircolors
  include_tasks: colors.yml

- name: Configure editorconfig
  include_tasks: editorconfig.yml

- name: Configure fish
  include_tasks: fish.yml
  when: '"fish" in shell.bin'

- name: Configure git
  include_tasks: git.yml

- name: Configure lvim
  include_tasks: lvim.yml

- name: Configure maven
  include_tasks: maven.yml
  when: configure.maven

- name: Configure ssh
  include_tasks: ssh.yml
  when: configure.ssh

- name: Configure wezterm
  include_tasks: wezterm.yml
  when: terminal.app | default(omit) == 'wezterm'

- name: Configure zellij
  include_tasks: zellij.yml
  when: terminal.multiplexer == 'zellij'

- name: Configure starship
  include_tasks: starship.yml

- name: Configure k9s
  include_tasks: k9s.yml

- name: Configure python
  include_tasks: python.yml

- name: Configure just
  include_tasks: just.yml

- name: Configure bat
  include_tasks: bat.yml
