- name: Copy ssh configuration
  copy:
    src: files/ssh/
    dest: $HOME/.ssh

# TODO: merge all config_* files into $HOME/.ssh/config
# TODO: append all public keys into $HOME/.ssh/authorized_keys
