- name: Create config directory
  file:
    path: "{{ ansible_user_dir }}/.ssh"
    state: directory
    recurse: true

- name: Configure ssh
  template:
    src: ssh/config.j2
    dest: "{{ ansible_user_dir }}/.ssh/config"
    mode: 0600
