- name: Place tmux configuration
  file:
    src: "{{ role_path }}/files/tmux/.tmux.conf"
    dest: $HOME/.tmux.conf
    state: link

- name: Install tpm
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: $HOME/.tmux/plugins/tpm
    update: true
