- name: Include Debian related tasks
  include_tasks: debian/main.yml
  args:
    apply:
      become: true
  when: ansible_os_family == "Debian"

- name: Include RedHat related tasks
  include_tasks: redhat/main.yml
  args:
    apply:
      become: true
  when: ansible_os_family == "RedHat"

- name: "Include Mac related tasks"
  include_tasks: mac/main.yml
  when: ansible_os_family == "Darwin"

- include_tasks: flatpak.yml
  when: ansible_os_family != "Darwin"