- name: Install packages for Fedora
  dnf:
    name:
      - glibc-langpack-tr
      - tmux
      - neofetch
      - neovim
      - exa
      - jq
      - silversearcher-ag
      - bat
      - fish

- name: Install GUI packages for Fedora
  dnf:
    name:
      - caffeine
  when: ansible_env.DISPLAY is defined

# TODO: overgrive
