- name: Install system76 packages if necessary
  include_tasks: system76.yml
  when: |
    ansible_system_vendor is defined
      and ansible_system_vendor == "System76"
      and not inside_container

- name: Configure YUM repo of tailscale
  include_tasks: tailscale.yml
  when: not inside_container

- name: Install Fedora Silverblue packages
  include_tasks: silverblue.yml
  when: ansible_pkg_mgr == "atomic_container"

- name: Install packages
  dnf:
    name:
      - glibc-langpack-tr
      - tmux
      - neofetch
      - neovim
      - exa
      - jq
      - the_silver_searcher
      - bat
      - fish
  when: ansible_pkg_mgr == "dnf"
