- name: Install system76 packages if necessary
  include_tasks: system76.yml
  when: |
    ansible_system_vendor is defined
      and ansible_system_vendor == "System76"
      and not inside_container

- name: Configure YUM repo of tailscale
  include_tasks: tailscale.yml
  when: not inside_container

- name: Configure YUM repo of globalprotect-openconnect
  yum_repository:
    name: globalprotect-openconnect
    description: globalprotect-openconnect
    baseurl: https://download.copr.fedorainfracloud.org/results/yuezk/globalprotect-openconnect/fedora-$releasever-$basearch/
    gpgkey: https://download.copr.fedorainfracloud.org/results/yuezk/globalprotect-openconnect/pubkey.gpg

- name: Install packages
  include_tasks: silverblue.yml
  when: ansible_pkg_mgr == "atomic_container"

- name: Install packages
  dnf:
    name:
      - glibc-langpack-tr
      - tmux
      - neofetch
      - neovim
      - exa
      - jq
      - the_silver_searcher
      - bat
      - fish
  when: ansible_pkg_mgr == "dnf"

- name: Install GUI packages
  dnf:
    name:
      - globalprotect-openconnect
  when: ansible_pkg_mgr == "dnf" and ansible_env.DISPLAY is defined