- name: Configure YUM repo of tailscale
  include_tasks: tailscale.yml

- name: Install Fedora Silverblue packages
  include_tasks: silverblue.yml
  when: ansible_pkg_mgr == "atomic_container"

- name: Install packages
  dnf:
    name:
      - glibc-langpack-tr
      - tmux
      - neofetch
      - neovim
      - exa
      - jq
      - silversearcher-ag
      - bat
      - fish
  when: ansible_pkg_mgr == "dnf"
