# TODO: package removal from base

- name: Install packages for Fedora Silverblue
  community.general.rpm_ostree_pkg:
    name:
      - uptimed
      - tailscale
  notify:
    - Restart system

- name: Install GUI packages for Fedora Silverblue
  community.general.rpm_ostree_pkg:
    name:
      - gnome-tweaks
      - gnome-shell-extension-pop-shell
      - python3-psutil
      - python3-google-api-client
      - python3-oauth2client
      - globalprotect-openconnect
  when: ansible_env.DISPLAY is defined
  notify:
    - Restart system

- name: Install overgrive for Fedora Silverblue
  community.general.rpm_ostree_pkg:
    name: https://www.thefanclub.co.za/sites/default/files/public/overgrive/overgrive-3.3.10.noarch.rpm
  when: ansible_env.DISPLAY is defined
  notify:
    - Restart system

- name: Flush handlers
  meta: flush_handlers
