- name: Enable system76 repo
  yum_repository:
    name: system76
    description: system76
    baseurl: https://download.copr.fedorainfracloud.org/results/szydell/system76/fedora-$releasever-$basearch
    gpgkey: https://download.copr.fedorainfracloud.org/results/szydell/system76/pubkey.gpg

- name: Install system76 packages
  community.general.rpm_ostree_pkg:
    name:
      - system76-driver
      - system76-firmware
      - system76-power
      - firmware-manager
      - system76-keyboard-configurator
  notify:
    - Restart system

- name: Flush handlers
  meta: flush_handlers

- name: Enable power daemon
  systemd:
    name: system76-power
    enabled: true
    state: started

- name: Enable power-wake
  systemd:
    name: system76-power-wake
    enabled: true
    state: started

- name: Enable firmware daemon
  systemd:
    name: system76-firmware-daemon
    enabled: true
    state: started

- name: Enable firmware notifier
  become: false
  systemd:
    scope: user
    name: com.system76.FirmwareManager.Notify.timer
    enabled: true
    state: startedƒ