- name: Ensure that local bin directory exists
  file:
    path: "{{ ansible_user_dir }}/.local/bin"
    state: directory
    recurse: true

- name: Ensure that installer is executed
  script: files/install_{{ item }}.sh
  loop: "{{ installers }}"
