if has("gui_macvim")
    set guifont=DejaVu\ Sans\ Mono\ for\ Powerline:h11
    set guioptions-=m  " no menu
    set guioptions-=T  " no toolbar
    set guioptions-=l
    set guioptions-=L
    set guioptions-=r  " no scrollbar
    set guioptions-=R
    set guicursor+=a:blinkon0
    set guicursor=a:hor20-Cursor

    inoremap <D-Return> <esc>o
    nnoremap <D-j> !python -m json.tool<cr>
    nnoremap <S-F> :set fullscreen!<cr>

    noremap <silent> <C-Right> <c-w>l
    noremap <silent> <C-Left> <c-w>h
    noremap <silent> <C-Up> <c-w>k
    noremap <silent> <C-Down> <c-w>j
endif
