syn on
filetype off
filetype plugin indent on

" Bundles
source ~/.vim/bundles.vim

" Generic
set noeb  " no beeps
set bs=indent,eol,start  " Makes backspace key more powerful.
set spr  " Split vertical windows right to the current windows
set sb  " Split horizontal windows below to the current windows
set aw  " Automatically save before :next, :make etc.
set ar  " Automatically reread changed files without asking me anything
set sm  " Do not show matching brackets by flickering
set enc=utf-8
set fencs=utf-8
set nocp
set acd
set ai
set si
set cin
set bg=dark
set et
set sta
set sw=4
set sts=4
set ts=4
set wig=*.pyc
set ic
set scs
set hls
set is
set sr
set hi=1000
set ul=1000
set noswf
set nobk
set nu
set rnu
set ls=2

" Bindings
map <C-s> :w<cr>
map <C-w> :bd<cr>
map <C-q> :qa!<cr>
nmap <Tab> :CtrlPBuffer<cr>
nmap gh <Plug>GitGutterNextHunk
nmap gH <Plug>GitGutterPrevHunk
nnoremap <silent> <C-Right> <c-w>l
nnoremap <silent> <C-Left> <c-w>h
nnoremap <silent> <C-Up> <c-w>k
nnoremap <silent> <C-Down> <c-w>j

" Subsettings
let g:netrw_liststyle=3

let g:airline#extensions#tabline#enabled=1
let g:airline_powerline_fonts=1
let g:airline_detect_paste=1
let g:airline_detect_modified=1

let g:ctrlp_working_path_mode = 'ra'
let g:ctrlp_by_filename = 1
let g:ctrlp_match_window_bottom = 0
let g:ctrlp_max_height = 10
let g:ctrlp_switch_buffer = 'et'  " jump to a file if it's open already
let g:ctrlp_use_caching = 1
let g:ctrlp_clear_cache_on_exit=0
let g:ctrlp_mruf_max = 250
let g:ctrlp_custom_ignore = {
    \ 'dir':  '\v[\/]\.(git|hg|svn|build)$',
    \ 'file': '\v\.(exe|so|dll)$',
    \ 'link': 'SOME_BAD_SYMBOLIC_LINKS',
    \ }

" Theme
colorscheme solarized
let g:airline_theme="dark"

" Shortcuts
iab chlog <c-r>=strftime("%Y-%m-%d")<cr>  Alper Kanat  <alperkanat@raptiye.org><cr><cr>

if has("gui_macvim")
    set guifont=Monaco\ for\ Powerline:h10
endif
