syn on
filetype off
filetype plugin indent on

" Bundles
source ~/.vim/bundles.vim

" Change leader key
let g:mapleader=","

" Generic
set noeb  " no beeps
set bs=indent,eol,start  " Makes backspace key more powerful.
set spr  " Split vertical windows right to the current windows
set aw  " Automatically save before :next, :make etc.
set ar  " Automatically reread changed files without asking me anything
set sm  " Do not show matching brackets by flickering
set cul  " highlight current line
set enc=utf-8
set fencs=utf-8
set nocp
set ai
set si
set cin
set bg=dark
set et
set sta
set sw=4
set sts=4
set ts=4
set wig=*.pyc
set ic
set scs
set hls
set is
set sr
set hi=1000
set ul=1000
set noswf
set nobk
set nu
set rnu
set ls=2
set list
set listchars=tab:▸\ ,eol:¬
set wrap
set textwidth=120
set formatoptions=qrn1
set colorcolumn=120
set fdm=indent
set fdl=99

" Bindings
nnoremap <C-s> :w<cr>
nnoremap <C-w> :q<cr>
nnoremap <C-x> :bd<cr>
nnoremap <C-q> :qa!<cr>
nnoremap <Tab> :CtrlPBuffer<cr>
nnoremap gh <Plug>GitGutterNextHunk
nnoremap gH <Plug>GitGutterPrevHunk

nnoremap <silent> <C-Right> <c-w>l
nnoremap <silent> <C-Left> <c-w>h
nnoremap <silent> <C-Up> <c-w>k
nnoremap <silent> <C-Down> <c-w>j
nnoremap <silent> <C-A-Left> :bp<cr>
nnoremap <silent> <C-A-Right> :bn<cr>

" Move lines around.
" We use <t> as the temporary register.
nnoremap <C-A-Up>    "tddk"tP
nnoremap <C-A-Down>  "tdd"tp
nnoremap <A-Down>  "tdd}"tp
nnoremap <A-Up>    "tdd{"tP

" sublime like enters
inoremap <S-Return> <esc>O
inoremap <C-Return> <esc>o

" tabs
inoremap <S-Tab> <C-o><<

" create new splits
nnoremap <leader>s :sp<cr>
nnoremap <leader>v :vs<cr>

" source file
nnoremap <leader>so :source %<cr>

nnoremap <S-F> :set fullscreen!<cr>
nnoremap t :set ft=

" Subsettings
let g:netrw_liststyle=3

let g:airline#extensions#tabline#enabled=1
let g:airline_powerline_fonts=1
let g:airline_detect_paste=1
let g:airline_detect_modified=1

let g:ctrlp_working_path_mode = 'ra'
let g:ctrlp_match_window_bottom = 0
let g:ctrlp_max_height = 10
let g:ctrlp_switch_buffer = 'et'  " jump to a file if it's open already
let g:ctrlp_use_caching = 1
let g:ctrlp_clear_cache_on_exit=0
let g:ctrlp_mruf_max = 250
let g:ctrlp_custom_ignore = {
    \ 'dir':  '\v[\/]\.(git|hg|svn|build)$',
    \ 'file': '\v\.(exe|so|dll)$',
    \ 'link': 'SOME_BAD_SYMBOLIC_LINKS',
    \ }

let g:syntastic_check_on_open=1
let g:syntastic_python_checkers=['flake8']
let g:syntastic_go_checkers=['gofmt']
let g:syntastic_javascript_checkers=['jsl']

" Theme
colorscheme solarized
let g:airline_theme="dark"

" Shortcuts
iab chlog <c-r>=strftime("%Y-%m-%d")<cr>  Alper Kanat  <alperkanat@raptiye.org><cr><cr>

" Actions
au BufWritePost .vimrc source %  " reload vimrc everytime it's updated
au BufWritePre *.py Isort  " isort saved py files
