export PATH="$HOME/.bin:$HOME/.local/bin:/usr/local/bin:$PATH"
export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="tunix"
ZSH_CUSTOM="$HOME/.oh-my-zsh-custom"

COMPLETION_WAITING_DOTS="true"
HIST_STAMPS="dd.mm.yyyy"

ZSH_TMUX_AUTOSTART="true"

# ssh-agent forwarding
zstyle :omz:plugins:ssh-agent agent-forwarding on
zstyle :omz:plugins:ssh-agent identities id_rsa
zstyle :omz:plugins:ssh-agent lifetime 4h

ZSH_TMUX_AUTOQUIT="false"
ZSH_TMUX_FIXTERM="true"

plugins=(
    cargo
    colored-man-pages
    command-not-found
    common-aliases
    copydir
    copyfile
    cp
    direnv
    docker
    docker-compose
    encode64
    extract
    git
    gitignore
    gradle
    history-substring-search
    httpie
    kubectl
    mosh
    mvn
    rsync
    rust
    ssh-agent
    sudo
    tmux
    ubuntu
    urltools
    vundle
    zrp
    zsh-autosuggestions
)

source $ZSH/oh-my-zsh.sh

# allow C-s, C-q and so on..
stty -ixon
