export PATH="$HOME/.bin:$HOME/.local/bin:/usr/local/bin:$PATH"
export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="tunix"
ENABLE_CORRECTION="true"
COMPLETION_WAITING_DOTS="true"
HIST_STAMPS="dd.mm.yyyy"
ZSH_CUSTOM="$HOME/.oh-my-zsh-custom"

# ssh-agent forwarding
zstyle :omz:plugins:ssh-agent agent-forwarding on
zstyle :omz:plugins:ssh-agent identities id_rsa
zstyle :omz:plugins:ssh-agent lifetime 4h

ZSH_TMUX_AUTOQUIT="false"
ZSH_TMUX_FIXTERM="true"

plugins=(
    aws
    brew
    colored-man-pages
    common-aliases
    copydir
    copyfile
    docker
    docker-compose
    doctl
    encode64
    extract
    git
    gitignore
    history-substring-search
    httpie
    kubectl
    mvn
    osx
    rsync
    ssh-agent
    sudo
    tmux
    urltools
    vundle
)

source $ZSH/oh-my-zsh.sh

# allow C-s, C-q and so on..
stty -ixon
