- name: Enable taps
  homebrew_tap:
    name:
      - homebrew/bundle
      - homebrew/cask
      - homebrew/cask-versions
      - homebrew/core
      - homebrew/services

- name: Install packages
  homebrew:
    name:
      - homebrew/cask/alacritty
      - bat
      - homebrew/cask/caffeine
      - direnv
      - exa
      - fish
      - fzf
      - htop
      - jetbrains-toolbox
      - jq
      - neovim
      - podman
      - tailscale
      - the_silver_searcher
      - tmux
      - uptimed
      - watch
      - wget
      - z
    update_homebrew: true
    upgrade_all: true