- name: Create config directory
  file:
    path: "{{ ansible_user_dir }}/.config/wezterm"
    state: directory
    recurse: true

- name: Install configuration file
  template:
    src: wezterm/wezterm.lua.j2
    dest: "{{ ansible_user_dir }}/.config/wezterm/wezterm.lua"
