- name: Download AWS Session Manager Plugin RPM
  get_url:
    url: "{{ aws.session_manager_plugin.url }}"
    dest: /tmp/session-manager-plugin.rpm
    mode: '0644'

- name: Ensure local bin directory exists
  file:
    path: "{{ ansible_user_dir }}/.local/bin"
    state: directory
    mode: '0755'

- name: Install AWS Session Manager Plugin from RPM
  shell: |
    mkdir -p /tmp/aws_session_manager
    cd /tmp/aws_session_manager
    rpm2cpio /tmp/session-manager-plugin.rpm | cpio -idmv
    cp /tmp/aws_session_manager/usr/local/sessionmanagerplugin/bin/session-manager-plugin "{{ ansible_user_dir }}/.local/bin/"
    chmod +x "{{ ansible_user_dir }}/.local/bin/session-manager-plugin"
  args:
    creates: "{{ ansible_user_dir }}/.local/bin/session-manager-plugin"