- name: Parse GNOME Shell version
  shell: gnome-shell --version | sed 's/[^0-9.]*\([0-9.]*\).*/\1/'
  register: r_gnome_shell_version_output
  changed_when: false
  when: shell_extension_ids is defined

- set_fact:
    gnome_shell_version: "{{ r_gnome_shell_version_output.stdout }}"
  when: shell_extension_ids is defined

- name: Get GNOME Shell extension info
  uri:
    url: "https://extensions.gnome.org/extension-info/?pk={{ item }}&shell_version={{ gnome_shell_version }}"
    return_content: yes
  loop: "{{ shell_extension_ids }}"
  register: r_gnome_extension_info
  when: shell_extension_ids is defined

- name: Install extension
  include_tasks: install_extension.yml
  vars:
    gnome_extension_info: "{{ item.json }}"
  loop: "{{ r_gnome_extension_info.results }}"
  when: shell_extension_ids is defined

- name: Enable extensions
  command: "gnome-extensions enable -q {{ item }}"
  loop: "{{ enabled_extensions }}"
  when: enabled_extensions is defined

- name: Disable extensions
  command: "gnome-extensions disable -q {{ item }}"
  loop: "{{ disabled_extensions }}"
  when: disabled_extensions is defined

# TODO: install system76-power GNOME extension