- name: Configure YUM repo of tailscale
  include_tasks: tailscale.yml

- name: Install Fedora Silverblue packages
  include_tasks: silverblue.yml
  when: ansible_pkg_mgr == "atomic_container"

- name: Install Fedora packages
  include_tasks: fedora.yml
  when: ansible_pkg_mgr == "dnf"
