- name: Include Debian related tasks
  include_tasks: debian/main.yml
  args:
    apply:
      become: true
  when: ansible_os_family == "Debian"

- name: Include RedHat related tasks
  include_tasks: redhat/main.yml
  args:
    apply:
      become: true
  when: ansible_os_family == "RedHat"

- include_tasks: flatpak.yml

# TODO: snaps (bpytop, httpie, yq, hugo, gradle, kubectl, k9s)
# TODO: rust
# TODO: go
