FROM registry.fedoraproject.org/fedora-toolbox:36

# https://jurf.github.io/2020/03/24/vscode-toolbox/

RUN dnf -y update \
  && dnf -y install \
  @development-tools \
  openssh-server \
  && dnf clean all

RUN mkdir /cargo /rustup

ENV CARGO_HOME=/cargo \
  RUSTUP_HOME=/rustup \
  PATH=/cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

RUN curl https://sh.rustup.rs -sSf | sh -s -- -y --no-modify-path

RUN chgrp -R wheel /cargo /rustup \
  && chmod -R g=u /cargo /rustup

RUN /usr/libexec/openssh/sshd-keygen rsa \
  && /usr/libexec/openssh/sshd-keygen ecdsa \
  && /usr/libexec/openssh/sshd-keygen ed25519

COPY vscode_ssh_config.conf /etc/ssh/sshd_config.d/vscode.conf
