system76:
  enabled: false

mirrors:
  - path: /etc/apt/sources.list
    pattern: http://archive.ubuntu.com
    url: http://tr.archive.ubuntu.com

flatpak_packages:
  - com.belmoussaoui.Decoder
  - com.belmoussaoui.Obfuscate
  - com.discordapp.Discord
  - com.getpostman.Postman
  - com.github.gi_lom.dialect
  - com.github.huluti.Curtail
  - com.github.joseexposito.touche
  - com.github.rafostar.Clapper
  - com.github.tchx84.Flatseal
  - com.gitlab.newsflash
  - com.logseq.Logseq
  - com.mattjakeman.ExtensionManager
  - com.slack.Slack
  - com.spotify.Client
  - com.system76.Popsicle
  - com.valvesoftware.Steam
  - com.visualstudio.code
  - de.haeckerfelix.Shortwave
  - dev.geopjr.Hashbrown
  - fr.handbrake.ghb
  - in.bharatkalluri.splash
  - io.github.seadve.Kooha
  - io.webtorrent.WebTorrent
  - md.obsidian.Obsidian
  - org.gimp.GIMP
  - org.gnome.Boxes
  - org.gnome.Characters
  - org.gnome.Cheese
  - org.gnome.Connections
  - org.gnome.DejaDup
  - org.gnome.Mahjongg
  - org.gnome.Maps
  - org.gnome.Mines
  - org.gnome.SoundRecorder
  - org.gnome.Weather
  - org.gnome.clocks
  - org.gnome.gitlab.YaLTeR.VideoTrimmer
  - org.gnome.gitlab.somas.Apostrophe
  - org.remmina.Remmina
  - org.telegram.desktop
  - org.videolan.VLC
  - us.zoom.Zoom

developer_tools:
  - com.jetbrains.IntelliJ-IDEA-Ultimate
  - org.freedesktop.Sdk.Extension.node14//21.08
  - org.freedesktop.Sdk.Extension.rust-stable//21.08
