- name: Build tool containers
  containers.podman.podman_image:
    name: "{{ item.name }}"
    path: "{{ role_path }}/files/{{ item.name }}"
  loop: "{{ tools }}"
  when: tools is defined

- name: Create box from image
  command: "toolbox create -i {{ item.name }} {{ item.name }}"
  loop: "{{ tools }}"
  when: tools is defined

- name: Execute user hooks for tools
  command: "toolbox run -c {{ item.0.name }} -- {{ item.1 }}"
  with_subelements:
    - "{{ tools | selectattr('user_hooks', 'defined') | list }}"
    - user_hooks

# - name: Expose apps of tools
#   command: "distrobox enter {{ item.0.name }} -- distrobox-export --app {{ item.1 }}"
#   with_subelements:
#     - "{{ tools | selectattr('expose', 'defined') | list }}"
#     - expose
