- name: Ensure flathub repo is enabled
  flatpak_remote:
    name: "{{ item.name }}"
    method: "{{ item.method | default('user') }}"
    flatpakrepo_url: "{{ item.url }}"
  loop: "{{ flatpak_repos }}"
  when: flatpak_repos is defined

# ansible 2.10 cannot accept lists inside flatpak plugin
- name: Install flatpaks
  flatpak:
    name: "{{ item.name }}"
    method: "{{ item.method | default('user') }}"
    remote: "{{ item.repo | default('flathub') }}"
  loop: "{{ flatpak_packages }}"
  when: flatpak_packages is defined

# ansible 2.10 cannot accept lists inside flatpak plugin
- name: Install external flatpaks
  flatpak:
    name: "{{ item.name }}"
    method: "{{ item.method | default('user') }}"
  loop: "{{ external_flatpak_packages }}"
  when: external_flatpak_packages is defined
  ignore_errors: true
