- name: Ensure that 1password apt key is configured
  apt_key:
    id: AC2D62742012EA22
    url: https://downloads.1password.com/linux/keys/1password.asc
    keyring: /usr/share/keyrings/1password-archive-keyring.gpg

- name: Ensure that 1password ppa is configured
  apt_repository:
    repo: deb [arch=amd64 signed-by=/usr/share/keyrings/1password-archive-keyring.gpg] https://downloads.1password.com/linux/debian/amd64 stable main
    filename: 1password
