- name: Enable 24h clock format
  dconf:
    key: "/org/gnome/desktop/interface/clock-format"
    value: "'24h'"

- name: Show date in clock
  dconf:
    key: "/org/gnome/desktop/interface/clock-show-date"
    value: "true"

- name: Show weekday in clock
  dconf:
    key: "/org/gnome/desktop/interface/clock-show-weekday"
    value: "true"

- name: Set text scaling factor
  dconf:
    key: "/org/gnome/desktop/interface/text-scaling-factor"
    value: "1.0"

- name: Set repeat for keyboard
  dconf:
    key: "/org/gnome/desktop/peripherals/keyboard/repeat"
    value: "true"

- name: Set repeat interval for keyboard
  dconf:
    key: "/org/gnome/desktop/peripherals/keyboard/repeat-interval"
    value: "uint32 30"

- name: Disable natural scrolling for mouse
  dconf:
    key: "/org/gnome/desktop/peripherals/mouse/natural-scroll"
    value: "false"

- name: Enable touchpad
  dconf:
    key: "/org/gnome/desktop/peripherals/touchpad/send-events"
    value: "true"

- name: Enable tap-to-click for touchpad
  dconf:
    key: "/org/gnome/desktop/peripherals/touchpad/tap-to-click"
    value: "true"

- name: Enable natural scrolling for touchpad
  dconf:
    key: "/org/gnome/desktop/peripherals/touchpad/natural-scroll"
    value: "true"

- name: Enable two finger scrolling for touchpad
  dconf:
    key: "/org/gnome/desktop/peripherals/touchpad/two-finger-scrolling-enabled"
    value: "true"

- name: Disable touchpad while typing
  dconf:
    key: "/org/gnome/desktop/peripherals/touchpad/disable-while-typing"
    value: "true"

- name: Disable over amplification
  dconf:
    key: "/org/gnome/desktop/sound/allow-volume-above-100-percent"
    value: "false"

- name: Enable system event sounds
  dconf:
    key: "/org/gnome/desktop/sound/event-sounds"
    value: "true"

- name: Show minimize & close buttons for windows
  dconf:
    key: "/org/gnome/desktop/wm/preferences/button-layout"
    value: "'appmenu:minimize,close'"

- name: Key binding for Switch to Workspace 1
  dconf:
    key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-1"
    value: "['<Super>1']"

- name: Key binding for Switch to Workspace 2
  dconf:
    key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-2"
    value: "['<Super>2']"

- name: Key binding for Switch to Workspace 3
  dconf:
    key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-3"
    value: "['<Super>3']"

- name: Key binding for Switch to Workspace 4
  dconf:
    key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-4"
    value: "['<Super>4']"

- name: Center new windows
  dconf:
    key: "/org/gnome/mutter/center-new-windows"
    value: "true"

- name: Enable night light
  dconf:
    key: "/org/gnome/settings-daemon/plugins/color/active"
    value: "true"

- name: Disable power button action
  dconf:
    key: "/org/gnome/settings-daemon/plugins/power/power-button-action"
    value: "'nothing'"

- name: Enable automatic location for weather
  dconf:
    key: "/org/gnome/shell/weather/automatic-location"
    value: "true"

- name: Weather locations
  dconf:
    key: "/org/gnome/shell/weather/locations"
    value: "[<(uint32 2, <('İzmir, Türkiye', '', false, [(0.67046357386984812, 0.47374190788000986)], [(0.670387510675717, 0.47371744010922612)])>)>]"

- name: World clocks locations
  dconf:
    key: "/org/gnome/shell/world-clocks/locations"
    value: "[<(uint32 2, <('San Francisco', 'KOAK', true, [(0.65832848982162007, -2.133408063190589)], [(0.659296885757089, -2.1366218601153339)])>)>, <(uint32 2, <('London', 'EGWU', true, [(0.89971722940307675, -0.007272211034407213)], [(0.89884456477707964, -0.0020362232784242244)])>)>, <(uint32 2, <('Berlin', 'EDDT', true, [(0.91746141594945008, 0.23241968454167572)], [(0.91658875132345297, 0.23387411976724018)])>)>, <(uint32 2, <('Amsterdam', 'EHAM', true, [(0.91280719879303418, 0.083194033496160544)], [(0.91367986341903151, 0.085812027374152042)])>)>]"

- name: Disable down arrow for clipboard indicator
  dconf:
    key: "/org/gnome/shell/extensions/clipboard-indicator/disable-down-arrow"
    value: "true"

- name: Set history size of clipboard indicator
  dconf:
    key: "/org/gnome/shell/extensions/clipboard-indicator/history-size"
    value: "200"

- name: Move selected item to top of clipboard indicator
  dconf:
    key: "/org/gnome/shell/extensions/clipboard-indicator/move-item-first"
    value: "true"

- name: Hide applications button in Pop Shell
  dconf:
    key: "/org/gnome/shell/extensions/pop-cosmic/show-applications-button"
    value: "false"

- name: Hide workspaces button in Pop Shell
  dconf:
    key: "/org/gnome/shell/extensions/pop-cosmic/show-workspaces-button"
    value: "false"

- name: Night switcher on-demand
  dconf:
    key: "/org/gnome/shell/extensions/nightthemeswitcher/time/always-enable-ondemand"
    value: "true"

- name: Night switcher on-demand button placement
  dconf:
    key: "/org/gnome/shell/extensions/nightthemeswitcher/time/ondemand-button-placement"
    value: "'menu'"

- name: Night switcher on-demand time
  dconf:
    key: "/org/gnome/shell/extensions/nightthemeswitcher/time/ondemand-time"
    value: "'night'"

- name: Night switcher manual mode
  dconf:
    key: "/org/gnome/shell/extensions/nightthemeswitcher/time/manual-time-source"
    value: "true"

- name: Night switcher time source
  dconf:
    key: "/org/gnome/shell/extensions/nightthemeswitcher/time/time-source"
    value: "'ondemand'"

- name: Night switcher follow disable
  dconf:
    key: "/org/gnome/shell/extensions/nightthemeswitcher/time/nightlight-follow-disable"
    value: "false"

- name: Activate launcher with Super+Space
  dconf:
    key: "/org/gnome/shell/extensions/pop-shell/activate-launcher"
    value: "['<Super>space']"

- name: Enable tiling
  dconf:
    key: "/org/gnome/shell/extensions/pop-shell/tile-by-default"
    value: "true"

- name: Disable tiling hint
  dconf:
    key: "/org/gnome/shell/extensions/pop-shell/active-hint"
    value: "false"

- name: Enable smart gaps
  dconf:
    key: "/org/gnome/shell/extensions/pop-shell/smart-gaps"
    value: "true"

- name: Disable snapping windows to grids
  dconf:
    key: "/org/gnome/shell/extensions/pop-shell/snap-to-grid"
    value: "false"

- name: Tiling gap inner
  dconf:
    key: "/org/gnome/shell/extensions/pop-shell/gap-inner"
    value: "uint32 2"

- name: Tiling gap outer
  dconf:
    key: "/org/gnome/shell/extensions/pop-shell/gap-outer"
    value: "uint32 2"

- name: Hide window titles
  dconf:
    key: "/org/gnome/shell/extensions/pop-shell/show-title"
    value: "false"

- name: Alphabetize vitals
  dconf:
    key: "/org/gnome/shell/extensions/vitals/alphabetize"
    value: "true"

- name: Shown vitals
  dconf:
    key: "/org/gnome/shell/extensions/vitals/hot-sensors"
    value: "['_processor_average_', '_memory_usage_', '__network-download_max__', '__network-upload_max__']"

- name: Vitals position in panel
  dconf:
    key: "/org/gnome/shell/extensions/vitals/position-in-panel"
    value: "2"

- name: Hide storage in vitals
  dconf:
    key: "/org/gnome/shell/extensions/vitals/show-storage"
    value: "false"

- name: Show system vitals
  dconf:
    key: "/org/gnome/shell/extensions/vitals/show-system"
    value: "true"
