- name: Configure extensions
  include_tasks: extensions.yml

- name: Configure dconf keys
  include_tasks: dconf.yml

- name: Configure avatar
  include_tasks: avatar.yml
  args:
    apply:
      become: true
