- include_tasks: repo.yml

- name: Ensure that all packages are up-to-date
  apt:
    upgrade: true
    update_cache: true

- name: Ensure that packages are installed
  apt:
    name: "{{ item }}"
  loop: "{{ packages }}"

- name: Ensure that packages are installed
  apt:
    deb: "{{ item }}"
  loop: "{{ external_packages }}"
  when: external_packages is defined

- name: Ensure that package cache is clean
  apt:
    autoclean: true
    autoremove: true
