- name: Ensure that repo keys are configured
  apt_key:
    url: "{{ item.key }}"
  when: "'key' in item"
  loop: "{{ repos }}"

- name: Ensure that repos are enabled
  apt_repository:
    repo: "{{ item.repo }}"
    filename: "{{ item.name }}"
  loop: "{{ repos }}"