- name: Install system76 packages if necessary
  include_tasks: system76.yml
  when: ansible_system_vendor is defined and ansible_system_vendor == "System76"

- include_tasks: repo.yml

- name: "Ensure that {{ item }} are installed"
  community.general.rpm_ostree_pkg:
    name: "{{ item }}"
  when: ansible_pkg_mgr == "atomic_container"
  loop: "{{ packages }}"
  notify:
    - Restart system

- name: "Ensure that {{ item }} are installed"
  community.general.rpm_ostree_pkg:
    name: "{{ item }}"
  when: ansible_pkg_mgr == "atomic_container"
  loop: "{{ external_packages }}"
  notify:
    - Restart system

- name: "Ensure that {{ item }} is installed"
  dnf:
    name: "{{ item }}"
  when: ansible_pkg_mgr == "dnf"
  loop: "{{ packages }}"

- name: "Ensure that {{ item }} is installed"
  dnf:
    name: "{{ item }}"
  when: ansible_pkg_mgr == "dnf"
  loop: "{{ external_packages }}"

- name: Flush handlers
  meta: flush_handlers