- name: Install system76 packages if necessary
  include_tasks: system76.yml
  when: system76.enabled

- include_tasks: repo.yml

- name: Ensure that packages are installed
  community.general.rpm_ostree_pkg:
    name: "{{ item }}"
  when: ansible_pkg_mgr == "atomic_container"
  loop: "{{ packages }}"
  notify:
    - End playbook

- name: Ensure that packages are installed
  dnf:
    name: "{{ item }}"
  when: ansible_pkg_mgr == "dnf"
  loop: "{{ packages }}"

- name: Flush handlers
  meta: flush_handlers
